
<form action="/default/index/insert"
      method="post" >
    <label class="control-label" for="nombre">Nombre:</label>
    <div class="controls">
        <?php echo $this->form->name; ?>
    </div>
    <label class="control-label" for="apellido">Primer Apellido:</label>
    <div class="controls">
        <?php echo $this->form->lastName; ?>
    </div>
    <label class="control-label" for="apellido">Segundo Apellido:</label>
    <div class="controls">
        <?php echo $this->form->firstName; ?>
    </div>
    <label class="control-label" for="hobby">Hobby:</label>
    <div class="controls">
        <?php echo $this->form->hobby; ?>
    </div>
    <label class="control-label" for="email">Email:</label>
    <div class="controls">
        <?php echo $this->form->mail; ?>
    </div>
    <label class="control-label" for="estadio">Estado:</label>
    <div class="controls">
        <?php echo $this->form->flagAct; ?>
    </div>
     <div class="controls">
        <?php echo $this->form->enviar; ?>
    </div>
</form>